### ISSUE TITLE
Error: Cannot find module 'express'

### ISSUE THREAD

**Issue by jfrance1** [ItsFuego/Captcha-Solver#1]
App threw an error during load
Error: Cannot find module 'express'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/Users/jfrance/git/Captcha-Solver/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/jfrance/git/Captcha-Solver/main.js:5:17)
    at Object.<anonymous> (/Users/jfrance/git/Captcha-Solver/main.js:125:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)

**Comment by sashapisdets** [comment]
npm install express --save
